### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by dennisjcox** [flickr-downloadr/flickr-downloadr-gtk#101]
[flickrdownloadr.log](https://github.com/flickr-downloadr/flickr-downloadr-gtk/files/3026549/flickrdownloadr.log)

Hi - giving the application a try and I got a unhandled exception off the bat. I'm sure its something silly that I did wrong.

**Comment by tamrajohnosn** [comment]
I'm having the same problem. I'm guessing it still isn't resolved?

**Comment by cutedaffodil** [comment]
Duplicate of #103
