### ISSUE TITLE
Unhandled Exception (includes logs & screens)

### ISSUE THREAD

**Issue by sdean7855** [flickr-downloadr/flickr-downloadr-gtk#103]
Invoke flickr-downloadr, get intro screen. 
Config Preferences to all logs
![FlickrDownloadr3 2 0 1-UnhandledExeption-PreferencesScreen](https://user-images.githubusercontent.com/31915700/56848041-f0cd5780-68b1-11e9-8d55-eef18f5569fc.jpg)
Go back to Intro screen, click on Continue, immediately get Exception
![FlickrDownloadr3 2 0 1-UnhandledExeption-AfterHittingContinue](https://user-images.githubusercontent.com/31915700/56848053-19555180-68b2-11e9-9dd8-7c2be2c45553.jpg)

Log attached
[flickrdownloadr.log](https://github.com/flickr-downloadr/flickr-downloadr-gtk/files/3123734/flickrdownloadr.log)

**Comment by AmphySuperTramp** [comment]
I have this problem too..

**Comment by isjac777** [comment]
I also have this problem on Mac OSX 10

**Comment by isjac777** [comment]
@cutedaffodil can you help us?

**Comment by cutedaffodil** [comment]
I’m sorry to hear about this issue - but unfortunately I do not use the app anymore and do not have the bandwidth now to look into/fix it.

If someone else can fix it and create a PR, I can merge it in

**Comment by W1N9Zr0** [comment]
@cutedaffodil: Pull request #104 submitted!

**Comment by cutedaffodil** [comment]
Thank you, @W1N9Zr0 - this is now merged, pushed, built and available as installers/update.

Can you (or someone else) please confirm that this issue is now resolved?

**Comment by W1N9Zr0** [comment]
Latest release works for me on Windows, thanks!
