### ISSUE TITLE
Can't login to my Flickr account (Page not found after authorizing app) 

### ISSUE THREAD

**Issue by etagwerker** [flickr-downloadr/flickr-downloadr-gtk#118]
Hi there, 

When I try to sign in using Mac OS X (Safari) I get this screen: 

![Screen Shot 2020-06-27 at 11 41 13 AM](https://user-images.githubusercontent.com/17584/85926135-3ea16f00-b86b-11ea-8e9d-9a447dedccb6.png)

While it takes me to this page at Flickr.com: 

![Screen Shot 2020-06-27 at 11 41 29 AM](https://user-images.githubusercontent.com/17584/85926140-4d882180-b86b-11ea-8db9-fe8738f60127.png)

Then when I click authorize I end up in this page: 

![Screen Shot 2020-06-27 at 11 41 36 AM](https://user-images.githubusercontent.com/17584/85926154-5da00100-b86b-11ea-8265-cd99e2f0add7.png)

Do you know why it is failing? Should I try using another browser as my default browser?

Please let me know.

Thanks!

**Comment by robermann** [comment]
Edit the location bar: http://  (not https://, remove the 's')

**Comment by etagwerker** [comment]
@robermann I can confirm that manually changing the URL in the browser fixes it for me.
