### ISSUE TITLE
*.deb package is of bad quality

### ISSUE THREAD

**Issue by Blackbaud-DavidKeegan** [flickr-downloadr/flickr-downloadr-gtk#12]
When loading flickrdownloadr_1.0.2.5-0_amd64.deb on ubuntu 14.10

The package is of bad quality
The installation of a package which violates the quality standards isn't allowed. This could cause serious problems on your computer. Please contact the person or organisation who provided this package file and include the details beneath.

Lintian check results for~/Downloads/flickrdownloadr_1.0.2.5-0_amd64.deb:
Skipping~/Downloads/flickrdownloadr_1.0.2.5-0_amd64.deb: syntax error at line 15: Cannot parse line "Depends : mono-complete, gtk-sharp3"

You are still able to 'ignore and install' after this message

**Comment by 3v1n0** [comment]
Well, you can't do this using deb or rpm because they act at super-user space, and this is something user related.

What you can do instead is adding a bash script installed as `/usr/bin/flickr-downloader` such as

```bash
#!/bin/bash

if [ ! -f ~/.config/flickr-downloadr/token.repos ]; then
  mozroots --import --ask-remove
fi

/opt/flickrdownloadr/bin/flickr-downloadr.exe
```

That just performs this thing once per user.

**Comment by floydpink** [comment]
Thanks @3v1n0 - I will include this into the launcher script

**Comment by floydpink** [comment]
@3v1n0 - The launcher script has been tweaked to run the `mozroots --import --sync` on [the first run](https://github.com/flickr-downloadr/flickr-downloadr-gtk/commit/91ad4c6e979faf1861f21f51b7a46a4f332f9941).

**Comment by CGarces** [comment]
I'm working on that

- [ ] Folder structure not match with a standard Debian program. See [some information].(https://sites.google.com/site/vysakhp/articles/create-debian-packages-for-mono-applications).
- [ ] The current package have too many dependencies (195 packages).
- [ ] Gtk-sharp3 dependency is incorrect, Gtk-sharp2 is the one used by the installer 
- [ ] I think that must be updated to 3.12.0 to use cert-sync
