### ISSUE TITLE
beta 3.3.2.1: SSL-Error 

### ISSUE THREAD

**Issue by HDValentin** [flickr-downloadr/flickr-downloadr-gtk#123]
I get the following Error in Firefox, on Windows 10, after granting access to the software:
"SSL_ERROR_RX_RECORD_TOO_LONG"

![Zwischenablage01](https://user-images.githubusercontent.com/1276955/99193261-31ccdb80-2778-11eb-9f34-8b873653a184.jpg)

**Comment by cutedaffodil** [comment]
@HDValentin - can you please check if the workaround mentioned [here](https://github.com/flickr-downloadr/flickr-downloadr-gtk/issues/113#issuecomment-609101656) helps?

**Comment by HDValentin** [comment]
Yes this helped. Changed manually from https to http...
