### ISSUE TITLE
Installer 3.3.2.2 not open in Os X 10.11.6

### ISSUE THREAD

**Issue by MacTerrassa** [flickr-downloadr/flickr-downloadr-gtk#127]
Hi:
The version I had installed does not authenticate on flick due to a problem with SSL: SSL_ERROR_RX_RECORD_TOO_LONG.
Under the current version 3.3.2.2 and the installer does not open on my mac with OS X 10.11.6
The crash message is:
Time Awake Since Boot: 4400 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

kernel messages:

VM Regions Near 0x1034522b8 (cr2):
    VM_ALLOCATE            000000010035f000-0000000100360000 [    4K] rw-/rwx SM=ALI  
--> 
    STACK GUARD            00007fff5bc00000-00007fff5f400000 [ 56.0M] ---/rwx SM=NUL  stack guard for thread 0

Thread 0 Crashed:
0   dyld                          	0x00007fff6d622000 _dyld_start + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x000000000000000d  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007fff5fbffbd8
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x00007fff6d622000  rfl: 0x0000000000000201  cr2: 0x00000001034522b8
  
Logical CPU:     0
Error Code:      0x0200003b
Trap Number:     133

I'm going to see if there is an intermediate version that works for me, but what is the problem, have the requirements changed, and now I need 10.12 or any other version higher than the one I have installed, 10.11?

I think I have installed it on another mac with Catalina (10.15) without problem, and your website still establishes a requirement of 10.6 so it should work or not?

Regards

Jose Luis

**Comment by MacTerrassa** [comment]
The problem seems to be related to the invalid signature, and the previous version 3.3.2.1 gives me the same error message. However, the version that I already have installed opens correctly, and does not install anything as it is identical.
Regards
Jose Luis

**Comment by cutedaffodil** [comment]
@MacTerrassa - can you please check if the workaround mentioned [here](https://github.com/flickr-downloadr/flickr-downloadr-gtk/issues/113#issuecomment-609101656) helps?

**Comment by MacTerrassa** [comment]
Hello, the proposal to modify the authentication link manually from https to http, works correctly to identify from the previous version.
This fixes my problem with the old version I had installed that I couldn't get before.
However, the problem with the last two versions remains. I have downloaded the disk images again, to check if it was a failure in my previous download, and it keeps giving me the same error message in the signature. I can't install anything then. At least now I can try the old version again, a workaround. Thanks.

**Comment by MacTerrassa** [comment]
I have also tried to change in system preferences to allow the installation of applications from anywhere (third option), 
since I normally use the second one: Mac App Store and identified developers, but it keeps giving me the same fault with the same message of Code Signature Invalid. 
I understand that by declaring the seal invalid, it no longer allows its installation even allowing all installers.
Regards
Jose Luis

**Comment by sjks-creator** [comment]
The installer: flickr downloadr (v3.3.2.2).dmg doesn't open under Mac OS 11.1. 
It reports downloadr (v3.3.2.2).dmg is broken and can't be opened. 
Any idea what to do?

**Comment by MacTerrassa** [comment]
In my case, and with 10.11 El Capitan, the zip is unzipped as a dmg image, and mounted on the desktop. What's not working is the app inside it - double-clicking it closes again and presents me with the system error message from my first message.
On another computer, with 10.15 Catalina, I have installed it without any problem. Although you might have to go to preferences> security> general and hit the unsafe app authorization button. Something that the system does not warn, you have to realize it and shortly after trying to run the application. Because after a few minutes, it disappears. Increasingly, Apple is promoting the total closure of its platform. And without taking into account the user at all, without the slightest notice of what the problem is. When I have had to update, I have been thinking about it a lot for that very reason. I didn't make the change from El Capitan to Catalina, because of the fear that these changes generate in me, which reduce usability so much. And I have not yet dared with Big Sur, and apparently, I may keep the new mac with Catalina until they force me.

**Comment by MacTerrassa** [comment]
I have tried the new versions, and all of them keep giving me the same problem, until 3.3.3.2 at least, I can open the dmg, but the application does not open and generates a message of "Code signature invalid".

**Comment by cutedaffodil** [comment]
@MacTerrassa - sorry, I was not able to test this out until now.

Looks like this is because of a change in Gatekeeper settings in macOS Catalina - it does not allow opening apps that are from unidentified developers like us.

The below link provides a workaround that helps going around this limitation in Gatekeeper - please consider using it and see if that helps:

https://apple.stackexchange.com/questions/372084/macos-catalina-app-is-damaged-and-cant-be-opened-you-should-move-it-to-the-t/372208#372208

**Comment by MacTerrassa** [comment]
Maybe I did not explain myself well: I am using El Capitan 10.11 and this is where I cannot open any version from the 3.3.2.1 to 3.3.3.2. The last one that I can install and have installed is 3.3.1.1
Anyway, I have tried the xattr command as indicated, and it gives me the same result: double click on the app within the disk image, it jumps to the dock, but closes immediately.
And the message has been closed unexpectedly, the report will be sent to Apple with the content of the initial message.
I understood that also, the application quarantine had no effect if you dragged it to the downloads folder or an external disk. It doesn't work for me either.

**Comment by MacTerrassa** [comment]
In addition, precisely on another Mac that does have Catalina, I have not had any problem installing any of the versions that I have tried there. As I am not ahead, I do not know until which version I got there, but I think it is updated to the latest without any problem. I will check it again.

**Comment by lantrix** [comment]
> The below link provides a workaround that helps going around this limitation in Gatekeeper - please consider using it and see if that helps:
> 
> https://apple.stackexchange.com/questions/372084/macos-catalina-app-is-damaged-and-cant-be-opened-you-should-move-it-to-the-t/372208#372208

I'm using 10.15 and this was super helpful to get the download running thanks.

**Comment by MacTerrassa** [comment]
Thanks for the link, but I repeat my words again: 
In my new iMac with Catalina, I already installed the program correctly, without any problem to open the installer or the final program. What's more, now I see a new update, which I will try again tomorrow to install on Catalina.
My problem is with another previous iMac, which continues to work with El Capitan (mac os X 10.11) and which is the one that does not allow me to open the installer.
Neither by dragging the installer to the downloads folder, which is a trick for new systems and avoiding its controls (but in theory, not in El Capitan), nor to an external hard drive. In no case am I allowed to open it.
Neither by pressing control + open, nor by using the command mentioned in the link to change the quarantine attributes. Not doing it with xattred from Eclecticlight Software. Nor with some others that I found interesting to try. I have not managed to install it on El Capitan yet. Except for the old version that I mention above, and that can be motivated by some internal change that prevents it on the new versions. 
Which? No idea. But it seems to me that if the problem was just quarantine or permissions, I wouldn't be able to install older versions either, as if I can install up to one version 3.3.1.1

**Comment by MacTerrassa** [comment]
I just installed perfectly on my mac with 10.11.6 the latest version 3.4.01 from Flickr Downloadr. It seems they have finally fixed the problem.
I had not tried any of the intermediate versions I do not know if it has been in the last or any of these. 
Thanks for fixing it.
Regards
MacTerrassa
