### ISSUE TITLE
FlickR Downloader UI does not handle fractional scaling on Windows / UI looks tiny (with workaround)

### ISSUE THREAD

**Issue by loicraux** [flickr-downloadr/flickr-downloadr-gtk#128]
On my windows 10 laptop, I use a fractional scaling of 250% (in Start > Settings > Ease of Access > Display > Make Everything Bigger) so that UI objects (fonts, buttons, etc.) do not look too small.
However, with this fractional scaling, the flickr-downloader UI is totally messed up.

This is because GTK (and Mono's GTK#) does not support well Windows fractional scaling, see https://gitlab.gnome.org/GNOME/gtk/-/issues/1036

Maybe an update of GTK# version could fix this, I haven't checked if this is fixed in a more recent GTK release and/or GTK# release.

As a workaround, go to Start > Settings > Ease of Access > Display > Make Everything Bigger and select 100% (no scaling)

Consequently, I am able to run the latest Flickr-downloader version on Windows 10, (also with the https://localhost to http://localhost trick for app authorization), I just have to wear a pair of binoculars 🤣 :

![image](https://user-images.githubusercontent.com/3329077/104201340-f114da00-5429-11eb-8141-68e87e314447.png)

**Comment by cutedaffodil** [comment]
Thank you, @loicraux !
