### ISSUE TITLE
Make flickr-downloadr show up in Ubuntu Dash search

### ISSUE THREAD

**Issue by Blackbaud-DavidKeegan** [flickr-downloadr/flickr-downloadr-gtk#14]
Ubuntu install needs to move the downloadr*.desktop file to /usr/share/applications/ so that it will appear in the application section of the Dash search, and can be accessed/locked via launcher

**Comment by bhavikat** [comment]
I think flickr-downloadr would need root access to move the desktop file to /usr/share/applications. Should instead copy to ~/.local/share/applications/
