### ISSUE TITLE
Login failure

### ISSUE THREAD

**Issue by ppmax** [flickr-downloadr/flickr-downloadr-gtk#15]
Hi--

I downloaded the application and the Mono Framework and launched the app. I then click the Login button but the application then crashes (unhandled exception). I'm never prompted for credentials...? 

Version is 1.0.3.1

thx
PP

**Comment by floydpink** [comment]
@ppmax Could you please try the latest version (`1.0.4.1`) and see if that resolves the issue?

**Comment by ppmax** [comment]
Happy new year floydpink. I hope you had some time off from the daily grind. 

I grabbed the new installer, uninstalled the previous version, but am still getting the unhanded exception error. 

I dug through the flickrdownloadr.log located in the app bundle and found the URI for the UnauthorizedTokenRequest:
http://www.flickr.com/services/oauth/request_token

I can reach this no problem via my browser; the log also shows:
<log4j:event logger="DotNetOpenAuth.Http" timestamp="1420338479585" level="ERROR" thread="1"><log4j:message>http://www.flickr.com/services/oauth/request_token returned 417 ExpectationFailed: Expectation failed</log4j:message><log4j:properties><log4j:data name="log4japp" value="flickr-downloadr.exe" /><log4j:data name="log4net:Identity" value="" /><log4j:data name="log4net:HostName" value="mydevmachine.ppnet.loc" /><log4j:data name="log4jmachinename" value="mydevmachine.ppnet.loc" /><log4j:data name="log4net:UserName" value="paul" /></log4j:properties><log4j:locationInfo class="DotNetOpenAuth.Loggers.Log4NetLogger" method="ErrorFormat" file="" line="0" /></log4j:event>

So it appears the server is rejecting the token request? 

thx
PP

**Comment by floydpink** [comment]
Happy New Year! :)

Your assessment is right, it looks like the server is treating one of the requests a little differently in your case - what is intriguing is that I am not able to reproduce the error on my Mac.

I have attempted to fix it one more time - when you get time, could you kindly install and run the latest version (`1.1.0.2`) and post the updates?

**Comment by floydpink** [comment]
@ppmax Please reopen this issue if you're still getting the same error.
