### ISSUE TITLE
Flickr Downloadr crashes as soon as I start it.

### ISSUE THREAD

**Issue by ghost** [flickr-downloadr/flickr-downloadr-gtk#16]
I am currently using Windows 7 Ultimate x64 and when trying to start Flickr Downloadr it crashes right away. I have successfully installed the program and it has also appeared to install GTK properly.

The following is copied from the error dialog generated by Windows.

Problem signature:
Problem Event Name: CLR20r3
Problem Signature 01: flickr-downloadr.exe
Problem Signature 02: 1.0.3.1
Problem Signature 03: 54878a7e
Problem Signature 04: glib-sharp
Problem Signature 05: 2.12.0.0
Problem Signature 06: 52cb5aea
Problem Signature 07: 1bb
Problem Signature 08: 2c
Problem Signature 09: System.DllNotFoundException
OS Version: 6.1.7601.2.1.0.256.1
Locale ID: 1033
Additional Information 1: 0a9e
Additional Information 2: 0a9e372d3b4ad19135b953a78882e789
Additional Information 3: 0a9e
Additional Information 4: 0a9e372d3b4ad19135b953a78882e789

**Comment by floydpink** [comment]
Since all those DLLs are there in the folder `C:\Program Files (x86)\GtkSharp\2.12\bin`, I am not sure what else is causing this issue.

I would recommend trying the application from another system and see if that helps.

**Comment by xanathar** [comment]
Reproduced (as it happened on my system).

The solution is to manually add C:\Program Files (x86)\GtkSharp\2.12\bin (or whatever the GTK# path is) to the PATH environment var.

**Comment by floydpink** [comment]
Excellent - thank you, @xanathar 

@Kramerboy - Not sure if you're still interested, but this would serve as a good work around if the issue still persists for you.

**Comment by floydpink** [comment]
Yet another workaround for this issue is to manually uninstall GTKSharp from "Add Remove Programs" and to install v2.12.26 from [here](https://download.xamarin.com/GTKforWindows/Windows/gtk-sharp-2.12.26.msi)
