### ISSUE TITLE
Getting list of photos

### ISSUE THREAD

**Issue by vince68** [flickr-downloadr/flickr-downloadr-gtk#18]
The program is launched, I click to continue and I always get this message "Getting list of photos" and nothing else appears. My OS : ubuntu 14.04 x64 with french language.
I found a work arround, launch the program whith LANG=C on command line.

**Comment by floydpink** [comment]
Could you please run the app from the Terminal and see if that gives any error we can look at?

**Comment by vince68** [comment]
erros on terminal : 

(flickr-downloadr:10577): GLib-CRITICAL **: Source ID 7 was not found when attempting to remove it

(flickr-downloadr:10577): GLib-CRITICAL **: Source ID 9 was not found when attempting to remove it

(flickr-downloadr:10577): GLib-CRITICAL **: Source ID 8 was not found when attempting to remove it

(flickr-downloadr:10577): GLib-CRITICAL **: Source ID 5 was not found when attempting to remove it

(flickr-downloadr:10577): GLib-CRITICAL **: Source ID 56 was not found when attempting to remove it

(flickr-downloadr:10577): GLib-CRITICAL **: Source ID 55 was not found when attempting to remove it

(flickr-downloadr:10577): GLib-CRITICAL **: Source ID 54 was not found when attempting to remove it

(flickr-downloadr:10577): GLib-CRITICAL **: Source ID 120 was not found when attempting to remove it

(flickr-downloadr:10577): GLib-CRITICAL **: Source ID 121 was not found when attempting to remove

**Comment by vince68** [comment]
and with LANG=C : 

(flickr-downloadr:10597): GLib-CRITICAL **: Source ID 9 was not found when attempting to remove it

(flickr-downloadr:10597): GLib-CRITICAL **: Source ID 7 was not found when attempting to remove it

(flickr-downloadr:10597): GLib-CRITICAL **: Source ID 8 was not found when attempting to remove it

(flickr-downloadr:10597): GLib-CRITICAL **: Source ID 5 was not found when attempting to remove it

(flickr-downloadr:10597): GLib-CRITICAL **: Source ID 28 was not found when attempting to remove it

(flickr-downloadr:10597): GLib-CRITICAL **: Source ID 65 was not found when attempting to remove it

(flickr-downloadr:10597): GLib-CRITICAL **: Source ID 66 was not found when attempting to remove it

(flickr-downloadr:10597): GLib-CRITICAL **: Source ID 30 was not found when attempting to remove it

(flickr-downloadr:10597): GLib-CRITICAL **: Source ID 29 was not found when attempting to remove it

(flickr-downloadr:10597): GLib-CRITICAL **: Source ID 111 was not found when attempting to remove it

(flickr-downloadr:10597): GLib-CRITICAL **: Source ID 119 was not found when attempting to remove it

(flickr-downloadr:10597): GLib-CRITICAL **: Source ID 108 was not found when attempting to remove it

(flickr-downloadr:10597): GLib-CRITICAL **: Source ID 118 was not found when attempting to remove it

(flickr-downloadr:10597): GLib-CRITICAL **: Source ID 117 was not found when attempting to remove it

(flickr-downloadr:10597): GLib-CRITICAL **: Source ID 115 was not found when attempting to remove it

(flickr-downloadr:10597): GLib-CRITICAL **: Source ID 116 was not found when attempting to remove it

(flickr-downloadr:10597): GLib-CRITICAL **: Source ID 141 was not found when attempting to remove it

(flickr-downloadr:10597): GLib-CRITICAL **: Source ID 129 was not found when attempting to remove it

(flickr-downloadr:10597): GLib-CRITICAL **: Source ID 133 was not found when attempting to remove it

(flickr-downloadr:10597): GLib-CRITICAL **: Source ID 131 was not found when attempting to remove it

(flickr-downloadr:10597): GLib-CRITICAL **: Source ID 142 was not found when attempting to remove it

(flickr-downloadr:10597): GLib-CRITICAL **: Source ID 132 was not found when attempting to remove it

(flickr-downloadr:10597): GLib-CRITICAL **: Source ID 135 was not found when attempting to remove it

(flickr-downloadr:10597): GLib-CRITICAL **: Source ID 140 was not found when attempting to remove it

(flickr-downloadr:10597): GLib-CRITICAL **: Source ID 130 was not found when attempting to remove it

(flickr-downloadr:10597): GLib-CRITICAL **: Source ID 120 was not found when attempting to remove it

(flickr-downloadr:10597): GLib-CRITICAL **: Source ID 126 was not found when attempting to remove it

(flickr-downloadr:10597): GLib-CRITICAL **: Source ID 139 was not found when attempting to remove it

(flickr-downloadr:10597): GLib-CRITICAL **: Source ID 134 was not found when attempting to remove it

(flickr-downloadr:10597): GLib-CRITICAL **: Source ID 121 was not found when attempting to remove it

(flickr-downloadr:10597): GLib-CRITICAL **: Source ID 125 was not found when attempting to remove it

(flickr-downloadr:10597): GLib-CRITICAL **: Source ID 124 was not found when attempting to remove it

(flickr-downloadr:10597): GLib-CRITICAL **: Source ID 123 was not found when attempting to remove it

**Comment by floydpink** [comment]
These messages does not affect the functionality of the application and are therefore okay.

Since the workaround of setting the locale to `en-US` seems to be working, I am guessing this is something to do with running the application on other locales.

If you could please follow these steps to help troubleshoot the issue, that would be great:
1. Run the application with the `LANG=C`option and change the `Log Level` in Preferences to `ALL` 
2. Quit the application and re-run without the `LANG=C` option and please post the content of the log file

**Comment by vince68** [comment]
I have the logs but they are a little big to post them, So I send them to you via email.

**Comment by floydpink** [comment]
Thank you very much for opening this issue and helping to troubleshoot it. 

Looks like there is some code that uses the current locale/culture on the system the app is running on, to interpret some numbers to strings. This was a mistake and it should not have been using the user's current locale as all the number-string and string-number conversions are just internal within the application logic. 

Shall fix this and update here soon - I would appreciate if you would do one more round of testing after that to make sure it works without the `LANG=C` option

**Comment by vince68** [comment]
I tested your new version : 1.1.0.2 and I have got the same problem.

-------- Message original --------
Sujet : Re: [flickr-downloadr-gtk] Getting list of photos (Hari Menon8)
De : Hari Menon <notifications@github.com>
Pour : flickr-downloadr/flickr-downloadr-gtk 
<flickr-downloadr-gtk@noreply.github.com>
Date : 05/01/2015 06:30

**Comment by floydpink** [comment]
@vince68 - I think the latest version (`1.1.1.3`) will work fine on any locales - could you please check when you get time?

**Comment by vince68** [comment]
Perfect. I have a question did you plan this feature : photos selection by albums ?

**Comment by floydpink** [comment]
Thanks for the feedback.

Would you please open an another issue for tracking the new feature of viewing/downloading photos from albums/sets?
