### ISSUE TITLE
New feature request : download a album

### ISSUE THREAD

**Issue by vince68** [flickr-downloadr/flickr-downloadr-gtk#20]
Coudl you add the possibility of photo selection from an entire album. Selection from tags will be appreciate too.
In any case you software is a good tools for flickr.

**Comment by floydpink** [comment]
Email from another user for this and a related feature:
> The app works well at a basic level but UI is simply inefficient to get to anything but the first few dozen images in photostream. Basic filters for image selection would solve that. Such as, only show photos with XYZ tag or only display photos in XYZ album/set.

**Comment by floydpink** [comment]
Implemented support for albums in [v2.0.0.1](https://github.com/flickr-downloadr/flickr-downloadr-gtk/compare/v1.2.0.6...v2.0.0.1)

**Comment by vince68** [comment]
Good job, I test it and it works for me, thank you !

-------- Message original --------
Sujet : Re: [flickr-downloadr-gtk] New feature request : download a 
album (#20)
De : Hari Menon <notifications@github.com>
Pour : flickr-downloadr/flickr-downloadr-gtk 
<flickr-downloadr-gtk@noreply.github.com>
Date : 18/06/2015 22:29
