### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by jackschwarz** [flickr-downloadr/flickr-downloadr-gtk#24]
Installed via flickrdownloadr-1.1.1.4-osx-installer.app on OS X 10.10.3 and would like an uninstaller or guidance about how to fully remove all package contents that were installed.

**Comment by floydpink** [comment]
Running the Uninstaller at `/Applications/flickrdownloadr/uninstall.app` will uninstall the application, but the dependent library of Mono framework (which in turn bundles GTK# framework within it) will not be removed by the uninstaller as there could be other apps that are using these.

If you're certain that there are no other applications in the system that uses/needs Mono (and GTK#), please check the instructions here to remove them:

[Uninstalling Mono on Mac OS X](http://www.mono-project.com/docs/about-mono/supported-platforms/osx/#uninstalling-mono-on-mac-os-x)

**Comment by floydpink** [comment]
Please reopen the ticket if you still have the issue - thanks
