### ISSUE TITLE
Crashes on opening app

### ISSUE THREAD

**Issue by wendyverwet** [flickr-downloadr/flickr-downloadr-gtk#29]
Hi. I downloaded 25 images from an album and the app crashed. Since then it crashed upon opening. I' running OSX Yosemite 10.10.5 (14F27) on an early 2015 MBP.

**Comment by floydpink** [comment]
Thank you for raising this issue.

**Comment by completerevolution** [comment]
Same problem here.  If you delete the permissions on Flickr, you can open the app up again (after authentication), but each time you close the app - it fails to re-open.

MBP 13" 2010, OSX 10.11.2

**Comment by akseitz62** [comment]
I have the same issue. Worked yesterday and this morning...then crashed apparently and now crashes each time it starts. Uninstalled and reinstalled....no help...still crashes. Running on Mac El Capitan OSX 10.11.3
