### ISSUE TITLE
Not able to download photos into an external/portable hard drive

### ISSUE THREAD

**Issue by floydpink** [flickr-downloadr/flickr-downloadr-gtk#31]
Issue reported via email by a user who is on Mac OS X El Capitan

**Comment by KeeganEad** [comment]
Did you try navigating to [volumes]? It doesn't display or navigate directories in the typical way Finder would lead you to expect.


![image](https://cloud.githubusercontent.com/assets/26011894/23873431/5d30ff1a-0808-11e7-96da-b36da00c7860.png)

How it shows various hard drives, internal and external inside [volumes]
![image](https://cloud.githubusercontent.com/assets/26011894/23873479/8dacdf60-0808-11e7-8be2-ea4b78341a41.png)

**Comment by floydpink** [comment]
@KeeganEad - I will reply to the email to point them to this approach.

Thank you very much for taking the time to post a very helpful comment with screenshots!
