### ISSUE TITLE
Oops! Flickr doesn't recognise the API key this application is trying to use.

### ISSUE THREAD

**Issue by curious-jim** [flickr-downloadr/flickr-downloadr-gtk#43]
I can't authorize the app, looks like it's not registered on Flickr anymore

**Comment by floydpink** [comment]
Thanks for letting us know - will resolve this within a couple of days

**Comment by spidermitch0** [comment]
Glad to see there's activity on this!  Thanks for the dedication to all those that work on this!

**Comment by stadiumbound** [comment]
Having the same problem, just downloaded and tried to use this app today for the first time

**Comment by timtak** [comment]
Oops. I can't connect to flickr with flickr downloadr either.  Should this be fixed I would be very happy and grateful. It is a great program when it works.

**Comment by floydpink** [comment]
Thank you for your patience - I've not been able to find time to change the API key.

Hopefully I will be able to publish a new release will that resolves this issue.

**Comment by timtak** [comment]
Thank you very much!
Tim

**Comment by floydpink** [comment]
The process of getting the fix released is taking longer than I imagined but hopefully very soon this would be resolved.

**Comment by timtak** [comment]
Thank you!

m(._.)m

**Comment by floydpink** [comment]
Update: Only the Mac OS X version has issues now and if any of you are looking/waiting for Windows/Linux versions you could try out the v2.1.1.1 installers from [here](https://github.com/flickr-downloadr/flickr-downloadr.github.io/tree/deploy-v2.1.1.1/app/installer)

**Comment by floydpink** [comment]
Released v2.2.0.1 - https://flickrdownloadr.com/downloads/
