### ISSUE TITLE
Add album option to download all

### ISSUE THREAD

**Issue by Mech0z** [flickr-downloadr/flickr-downloadr-gtk#46]
Would be nice if it was possible to click "Download to albums" when downloading all photos,

Its pretty hard to srot them afterwards because they get datetime.today timestamp

**Comment by floydpink** [comment]
Thanks for the feedback and the suggestion - will try and put this into one of the options that can be set for downloading all the photos.

And I am guessing downloading each of the albums individually is probably not an option for you?

**Comment by Mech0z** [comment]
Of course its an option, the other would just be far easier :) but maybe I will try to clone it. Also just having an option to put photos in these folders would be nice Year\Month

As said the problem when downloading bulk is that file history says 30-12-2016 or whenever I downloaded it and therefore hard to sort afterwards

**Comment by Mech0z** [comment]
Can you maybe tell me the difference between ConsumerSecret and SharedSecret ?

When I applied for a flickr api key I got a Key and a secret

**Comment by floydpink** [comment]
The `SharedSecret` is any arbitrary string that is used as the key to encrypt fickr-provided "api key" (`ConsumerKey` in [the `Secrets.cs` module](https://github.com/flickr-downloadr/flickr-downloadr-gtk/blob/master/build-tools/Secrets.cs.in)) and flickr-provided "secret" (`ConsumerSecret`).

And this [unit test](https://github.com/flickr-downloadr/flickr-downloadr-gtk/blob/master/source/FloydPink.Flickr.Downloadr.UnitTests/HelperTests/CryptTests.cs#L11) should help generate the encrypted`ConsumerKey` and `ConsumerSecret` (with your specific `SharedSecret` being used as the `CryptKey` there).

All this is just to deter the sniffing of the official Api Key and Secret by increasing the barrier.

**Comment by Mech0z** [comment]
Never figured this out, any chance you could add this feature or make a more detailed guide to compiling the code :)

**Comment by bissquitt** [comment]
I second this request. Was looking for a fork to do just that. We have over 2000 albums in our flickr, sorting them after would be impossible, and selecting each 1 by 1 would be tedious. If I select an album and on the next page do download all, it does exactly what I want with naming the folder after the album...I just need it to do that for every album I have. This is the one feature I haven't seen in any other flickr downloader.

**Comment by floydpink** [comment]
See https://github.com/flickr-downloadr/flickr-downloadr-gtk/issues/82#issuecomment-436119409

**Comment by floydpink** [comment]
@Mech0z - also, the download albums feature was implemented a while ago

**Comment by bissquitt** [comment]
@floydpink - Downloading albums was implemented but that was not the request. You can't download multiple albums at once. I currently have hundreds of albums. Currently I have 2 options:

1) download all pictures and lose all metadata associated with which album it is in

2) download a single album, go back, wait for it to reload the list of albums, click the next one, spend a month doing this for each of the 100+ albums

**Comment by cutedaffodil** [comment]
Closed by 8964d5be7acc6dae7cd9c25da2afffc1e0c04a29
