### ISSUE TITLE
Installation error GTK

### ISSUE THREAD

**Issue by andreabs89** [flickr-downloadr/flickr-downloadr-gtk#49]
Hello,
I am getting the error in image below while installing.
Do you know how to solve it?

![flickrdownloadr_error](https://cloud.githubusercontent.com/assets/25879110/23101733/dfde749e-f69a-11e6-86e5-8d9eb29216d6.PNG)

Thank you,
Andrea

**Comment by Bodger17** [comment]
Same problem - I am guessing it is because it won't work on Windows 10.  I just tried it on a Win 7 laptop & it worked fine.

**Comment by floydpink** [comment]
Can you try the latest version and see if the error still persists?

I will reopen this issue if necessary- but closing it for now.

**Comment by andreabs89** [comment]
Still not working

**Comment by halkeye** [comment]
does your name have a space in it? I think it needs to be quoted.

![image](https://user-images.githubusercontent.com/110087/47892863-47803a00-de17-11e8-9f55-786a863039e5.png)

It showed the msiexec help in a popup window for me.

**Comment by jewiden** [comment]
Same error for min on Windows 10.
Running `%LocalAppData%\Temp\gtk-sharp.msi` manually and then re-reunning Flickr Downloader solved it.
