### ISSUE TITLE
Unrecognized image file format exception on launch

### ISSUE THREAD

**Issue by avinash** [flickr-downloadr/flickr-downloadr-gtk#50]
Hi,

I have installed flickr-downloader on my Fedora Linux 24 laptop and, on initial run, I get to authorize it with Flickr and choose the preferences. As soon as I click on save, I get the following exception:

`GLib.GException: Unrecognized image file format
  at FloydPink.Flickr.Downloadr.UI.Windows.BaseWindow+<HandleException>c__AnonStorey0.<>m__0 (System.Object , System.EventArgs ) <0x41bab150 + 0x00017> in <filename unknown>:0 
  at Gtk.Application+InvokeCB.Invoke () <0x41b35dc0 + 0x00021> in <filename unknown>:0 
  at GLib.Timeout+TimeoutProxy.Handler () <0x41b35cf0 + 0x00046> in <filename unknown>:0`

and the application crashes. On subsequent launches, I immediately get the same exception.

The "Unrecognized image file format" is very troubling.

Any idea?

Avinash

**Comment by floydpink** [comment]
Thank you for reporting this. Can you please do these to help me troubleshoot?

1. First, to destroy the saved preferences and login information by deleting `$HOME/.config/flickr-downloadr/`
2. Then after logging in again,  please change the log level to `ALL` from the Preferences screen and paste the log file contents after reproducing the crash. 

Thanks!

**Comment by robermann** [comment]
Probably my pull request #56 should fix this problem too.
