### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by theweazel** [flickr-downloadr/flickr-downloadr-gtk#51]
Im tryi ng to install on my windows 10 64 bit and I ge tthe following error:

problem running post-install step. Installation may not complete correctly

Error creating directory H:/ .flickr-downloadr

The progrma will not start after this, any ideas?

**Comment by floydpink** [comment]
It looks like you might not have access to write into the `H:\` drive.

You could temporarily add an environment variable named `HOME` that points to `%USERPROFILE%` and rerun the installer.  To see how to set an environment variable, see [this article](https://www.computerhope.com/issues/ch000549.htm)

**Comment by theweazel** [comment]
I do have access to write to the h drive it's my pers9nal network drive
________________________________

**Comment by robermann** [comment]
Uhm so your home directory is a network disk? Probably the software is appending "/.flickr-downloadr" to "H:", which is not a good idea :)

Try what has been said before: 

> add an environment variable named HOME that points to %USERPROFILE% and rerun the installer

>

**Comment by floydpink** [comment]
Please try again with the latest version and let us know if this issue needs to be reopened.
