### ISSUE TITLE
Saving with title as name overwrites files when multiple images have same title

### ISSUE THREAD

**Issue by MikeCroall** [flickr-downloadr/flickr-downloadr-gtk#52]
Implementing a simple check whether such a file already exists and appending (1), (2), or whatever number necessary would avoid this, allowing all images to be downloaded instead of some being overwritten.

**Comment by robermann** [comment]
In my fork I added a fix appending a sequential number if the image already exists.

**Comment by robermann** [comment]
(close the issue)
