### ISSUE TITLE
Fatal error, unhandled exception, Please raise and issue on the support site 

### ISSUE THREAD

**Issue by Coderx7** [flickr-downloadr/flickr-downloadr-gtk#53]
I just installed this application, ran it for the first time, set some settings and authorized it. then my internet connection got disconnected! and the app showed an error and exited.
upon restarting it again, I face with  an unresponsive application as shown bellow: 
![image](https://user-images.githubusercontent.com/5382892/28074048-d46e0b28-666c-11e7-8233-868b85f1233f.png)

which ultimately results in this : 
![image](https://user-images.githubusercontent.com/5382892/28074057-d9f2829a-666c-11e7-9bc2-9730b152c22e.png)

I even uninstalled and reinstalled it again, but nothing changed, it seems as if the settings saved! 
anyway what is wrong and how can I fix it ?

**Comment by robermann** [comment]
Hello,

today I got what seems a similar problem: in my case there was a corrupted image (with a size of 0 bytes). After I removed it, it worked as usual.

So try yourself by empting the cache folder:
![image](https://user-images.githubusercontent.com/2182986/28755943-88718c74-7565-11e7-8b97-033ed58e3047.png)

**Comment by robermann** [comment]
(I have pulled a fix for this error)
