### ISSUE TITLE
flickrdownloadr crashes when trying to download ~7k photos at once

### ISSUE THREAD

**Issue by philnate** [flickr-downloadr/flickr-downloadr-gtk#6]
I tried to download my photostream at once(about 7k items). The downloader tried to calculate the photos for a while and then simply shutdown without any further message. Looks like that it ran out of memory or so.
Think the downloader should either handle this number correctly (preferred) or limit the number of photos to download, alerting when trying to download more.

**Comment by floydpink** [comment]
@m2mexpert Could you please try the latest version (1.0.4.1) and let us know if the issue is resolved?
