### ISSUE TITLE
Write JSON-data to EXIF-data

### ISSUE THREAD

**Issue by olind** [flickr-downloadr/flickr-downloadr-gtk#61]
Hi,
First of all - I love this tool! I have managed to make a backup of all my flickr images.

What I'm after in the long run is to be able to migrate the images back into my own WordPress-website. One possible way to do it is to use Flickr Downloadr to get the images to my computer and then batch import them to WordPress. I did a bit of research and it seems like there are plugins for mass-importing images to WordPress already.

For this to work I would need to get the information from the json object into exif-data in the images. I tried to copy it from the json file to exif via exiftool but I couldn't :( Are there a chance that you can add so Flickr Downloadr puts the info to the Exif-data in the image as well? Would be really handy!

Thanks a million in advance!

**Comment by floydpink** [comment]
I agree that would be a nice enhancement to be implemented - but this is not a priority for us for now. Sorry!
