### ISSUE TITLE
Write Sets, Albums, Collections and Upload date to JSON file

### ISSUE THREAD

**Issue by olind** [flickr-downloadr/flickr-downloadr-gtk#62]
It would be really really useful if more information was migrated from flickr. As of today I get Title, Description and Keywords. Would it be possible to get the Sets / Albums / Collection names as well as the upload date?

Thanks a lot!

**Comment by floydpink** [comment]
I can accept a PR on this if you (or anyone else) can make this change.

**Comment by satmandu** [comment]
Upload date would be really useful. If the flickr API is being used then Date Posted and Date Taken are available via the getInfo call:

https://www.flickr.com/services/api/flickr.photos.getInfo.html

The getExif call also allows one to get the exif data, though I'm not sure if that's the original data in the photo or a composite set of data from edits of metadata on Flickr.

https://www.flickr.com/services/api/flickr.photos.getExif.html
