### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by chrisevers** [flickr-downloadr/flickr-downloadr-gtk#63]
I downloaded the 2.2.2.3 OSX version and used for a few days. Then it stopped working and I Unninstalled to reinstall it!

I used Clean My Mac for the unninstall and now when I try to reinstall it, it gives me a message that the installed version is the same or newer that the one installed.

Has anyone seen this?

**Comment by floydpink** [comment]
Can you please try again with the latest version and let us know if this issue needs to be reopened.

**Comment by chrisevers** [comment]
With the new version the App wont even open....
