### ISSUE TITLE
Why aren't the download packages updated

### ISSUE THREAD

**Issue by blackwhitekez** [flickr-downloadr/flickr-downloadr-gtk#65]
Who can have any faith there is any maintenance being done on this project
The download package is exactly the same edition that has not changed in 10 months. The package repository for Ubuntu has not been updated in more than a year.

It seems highly likely to get any recent versions of this software you may have to build the packages yourself.

The whole point of a beta (as this software is described) is testing, then you get new packages that are built regularly. One open source software product I test regularly is building new packages daily throughout their test program. Obviously that doesn't happen here.

**Comment by floydpink** [comment]
Please try again with the latest version and let us know if this issue needs to be reopened.
