### ISSUE TITLE
How to run from Ubuntu 17.10 terminal?

### ISSUE THREAD

**Issue by orschiro** [flickr-downloadr/flickr-downloadr-gtk#66]
Thanks for your work on this!

Installed it as follows:

    orschiro@x230:~$ sudo dpkg -i Downloads/flickrdownloadr_2.2.2.3-0_amd64.deb 

However, I cannot find the binary on Ubuntu 17.10. 

What's its name? How can I run it from the terminal?

**Comment by ryanddunn** [comment]
Same problem... my install went fine but can't figure out how to run it.

**Comment by floydpink** [comment]
please try `/opt/flickrdownloadr/flickrdownloadr`
