### ISSUE TITLE
videos downloaded as photos

### ISSUE THREAD

**Issue by philnate** [flickr-downloadr/flickr-downloadr-gtk#7]
I've noticed that rather than downloading the actual video, the app downloads just the preview photo for the video. Would be great if the app could instead download the movie.

**Comment by waveman777** [comment]
Hi there. Any updates on this one? I would be great to see the possibility do download videos in original size. Some of my albums I'd like to download are a mixture of photos and videos, and so far I only get thumbnails of videos instead the actual video files. Is there any setting which can change that behaviour?

I'd really appreciate some help.
Thank you! Fantastic app overall!
