### ISSUE TITLE
Unhandled Exception (flickrdownloadr-2.2.2.3-linux-x64)

### ISSUE THREAD

**Issue by tridral** [flickr-downloadr/flickr-downloadr-gtk#70]
After some successful downloads I am seeing an 'unhandled exception' after selecting an album and clicking to go to the next screen.  This seems to be true of all albums.  I have rebooted and uninstalled/reinstalled.  This is on Ubuntu.  I would appreciate any help.  Many thanks.

**Comment by tridral** [comment]
Update: It's not all albums.  I've been able to download some, but it is unpredictable as to what will work.  I have no idea what might be causing the problem.

**Comment by floydpink** [comment]
This might have been now resolved. Please try again with the latest version and let us know if this issue needs to be reopened.
