### ISSUE TITLE
hangs at the second stage

### ISSUE THREAD

**Issue by Mrakobes666** [flickr-downloadr/flickr-downloadr-gtk#72]
the program logs on, but statem hangs at the following stage, just the grey box and everything I've done wrong?

**Comment by Mrakobes666** [comment]
[url=http://i103.fastpic.ru/big/2017/1231/2f/44635cbd6dde382798ae42195f23382f.png][img]http://i101.fastpic.ru/big/2017/1231/c0/ac7a36855b1196e8e97c6238f2b662c0.png[/img][/url]

**Comment by floydpink** [comment]
Please try again with the latest version and let us know if this issue needs to be reopened.
