### ISSUE TITLE
Manifesto from Jan Gerd's website is prohibited for XLM documents on DTD

### ISSUE THREAD

**Issue by timtak** [flickr-downloadr/flickr-downloadr-gtk#74]
I just installed downloadr and it hangs on start up. It could be something to do with the fact that I installed it my D drive (C is SSD) but the error says it is because the licence from \Jan gerds website is no good. 

My windows is Japanese so the error log file is in Japanese. Sorry about that. 

Platform version information
	Windows 			: 6.1.7601.65536 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.7.2558.0 built by: NET471REL1
	clr.dll 			: 4.7.2563.0 built by: NET471REL1
	dfdll.dll 			: 4.7.2558.0 built by: NET471REL1
	dfshim.dll 			: 4.0.31106.0 (Main.031106-0000)

Source
	URL Location			: file:///C:/Users/TT/AppData/Roaming/Microsoft/Windows/Start%20Menu/Programs/Flickr.com/Downloadr.appref-ms%7C

Error Outline
	以下はエラーの概要です。これらのエラーの詳細はログに一覧表示されています。
	* C:\Users\TT\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Flickr.com\Downloadr.appref-ms| のライセンス認証により例外が発生しました。 次の失敗メッセージが検出されました:
		+ https://jan-gerd.com/ からマニフェストを読み取っているときに例外が発生しました。マニフェストが無効であるか、ファイルを開くことができなかった可能性があります。
		+ DTD の使用はこの XML ドキュメントでは禁止されています。

コンポーネント ストア トランザクションの失敗の概要
	トランザクション エラーは検出されませんでした。

警告
	この操作中に警告は発生しませんでした。

操作の進行状況
	* [2018/05/01 13:19:03] : C:\Users\TT\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Flickr.com\Downloadr.appref-ms| のライセンス認証が開始されました。
	* [2018/05/01 13:19:03] : 配置で指定されたように必要な更新チェックを実行しています。

エラーの詳細
	この操作中に次のエラーが検出されました。
	* [2018/05/01 13:19:04] System.Deployment.Application.InvalidDeploymentException (ManifestParse)
		- https://jan-gerd.com/ からマニフェストを読み取っているときに例外が発生しました。マニフェストが無効であるか、ファイルを開くことができなかった可能性があります。
		- ソース:System.Deployment
		- スタック トレース:
			場所 System.Deployment.Application.ManifestReader.FromDocument(String localPath, ManifestType manifestType, Uri sourceUri)
			場所 System.Deployment.Application.DownloadManager.DownloadDeploymentManifestDirect(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
			場所 System.Deployment.Application.DownloadManager.DownloadDeploymentManifest(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, IDownloadNotification notification, DownloadOptions options)
			場所 System.Deployment.Application.ApplicationActivator.PerformDeploymentUpdate(SubscriptionState& subState, String& errorPageUrl)
			場所 System.Deployment.Application.ApplicationActivator.ProcessOrFollowShortcut(String shortcutFile, String& errorPageUrl, TempFile& deployFile)
			場所 System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			場所 System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
			場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			場所 System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			場所 System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- 内部例外 ---
		System.Xml.XmlException
		- DTD の使用はこの XML ドキュメントでは禁止されています。
		- ソース:System.Xml
		- スタック トレース:
			場所 System.Xml.XmlTextReaderImpl.Throw(Exception e)
			場所 System.Xml.XmlTextReaderImpl.ParseDoctypeDecl()
			場所 System.Xml.XmlTextReaderImpl.ParseDocumentContent()
			場所 System.Deployment.Application.ManifestValidatingReader.XmlFilteredReader.Read()
			場所 System.Xml.XsdValidatingReader.Read()
			場所 System.Deployment.Application.ManifestReader.FromDocument(String localPath, ManifestType manifestType, Uri sourceUri)

コンポーネント ストア トランザクションの詳細
	トランザクション情報はありません。

**Comment by floydpink** [comment]
Looks like you’re using a different downloader.
