### ISSUE TITLE
Text/Keyword Search Please

### ISSUE THREAD

**Issue by timtak** [flickr-downloadr/flickr-downloadr-gtk#76]
Quite a lot of us have a lot of photos on Flickr. That means that a downloader that allows us to select by clicking requires that we move through several (hundred) pages of photos in the attempt to find the photos that we want to download. 

One way would be to first use Flickr's Organisr text search to create an album with the photos, and then download that using this software. But then, one can use the download a zip file feature of Organizr to download. 

Ideally there would be a text / keyword search. I would not care where the search takes place (titles/descriptions/tags - preferably all) but of course the ability to stipulate would be fun for some.

**Comment by robermann** [comment]
In my use case, I used Flickr web search to search for the images I wanted, then put them in a new album. Finally I used downloadr and put in "Search for Album Name" the album name or part of it. 

Please note that it searchs for partial names, so you can type "house" and it will get "householder", "housekeeper" and so on. I think it is the same of your proposed "Text Search".
