### ISSUE TITLE
"Search for Album Name" doesn't work

### ISSUE THREAD

**Issue by eigenwillig** [flickr-downloadr/flickr-downloadr-gtk#79]
The "Search for Album Name" never returns any result for me.

Operating System: Linux 4.16.8-1-ARCH

**Comment by robermann** [comment]
Do they contain special characters? Any error in the log file?

**Comment by eigenwillig** [comment]
I've just searching for "CIA", but the search results table always stays empty for me.

I've even tried to enter URLs there. Could you please add an option to directly enter them? I don't need the search, but there is no other way to use your tool. Thanks!

**Comment by robermann** [comment]
It only searches among your own album; do you have albums whose name contain CIA?

**Comment by eigenwillig** [comment]
And how to download other people's albums? Isn't that the purpose of this program?

**Comment by robermann** [comment]
It downloads only **your own** photostreams. From https://flickrdownloadr.com/:

> A cross-platform desktop application for Windows, Mac and Linux to download (all or selected) photos from your photostream in their original size along with their description, title and tags.
