### ISSUE TITLE
Silent crashes in the middle of long downloads?

### ISSUE THREAD

**Issue by DrFrankReade** [flickr-downloadr/flickr-downloadr-gtk#81]
Hello,

I'm attempting a large download of an entire archive, 16,000 images. I've had two completely silent, apparently error-free program "crashes" that may or may not have been actual crashes, but it just quit part way through the download. 

I'm retrying in admin mode and windows 7 compatibility mode. The computer in question is quite stable and hasn't been giving me any trouble. The internet connection is hard-wired and 300Mbit, although it appears to be all over the place and averaging 20 mbit, throttled on Flickr's end. 

I'd love to be more helpful, but the logs look to be pretty sparse, and I walk back to the computer and I just don't see anything. 

Can I start the program in a verbose mode? 

```
<log4j:event logger="FloydPink.Flickr.Downloadr.UI.MainClass" timestamp="1533151813730" level="INFO" thread="1"><log4j:message>Application Start.</log4j:message><log4j:properties><log4j:data name="log4jmachinename" value="Andrew-PC" /><log4j:data name="log4japp" value="flickr-downloadr.exe" /><log4j:data name="log4net:Identity" value="" /><log4j:data name="log4net:UserName" value="ANDREW-PC\Andrew" /><log4j:data name="log4net:HostName" value="Andrew-PC" /></log4j:properties><log4j:locationInfo class="FloydPink.Flickr.Downloadr.UI.MainClass" method="Main" file="" line="0" /></log4j:event>
<log4j:event logger="FloydPink.Flickr.Downloadr.UI.MainClass" timestamp="1533151813757" level="INFO" thread="1"><log4j:message>Found GTK# version 2.12.26</log4j:message><log4j:properties><log4j:data name="log4jmachinename" value="Andrew-PC" /><log4j:data name="log4japp" value="flickr-downloadr.exe" /><log4j:data name="log4net:Identity" value="" /><log4j:data name="log4net:UserName" value="ANDREW-PC\Andrew" /><log4j:data name="log4net:HostName" value="Andrew-PC" /></log4j:properties><log4j:locationInfo class="FloydPink.Flickr.Downloadr.UI.MainClass" method="CheckWindowsGtk" file="" line="0" /></log4j:event>
<log4j:event logger="FloydPink.Flickr.Downloadr.UI.MainClass" timestamp="1533151824186" level="INFO" thread="1"><log4j:message>Application Exit.</log4j:message><log4j:properties><log4j:data name="log4jmachinename" value="Andrew-PC" /><log4j:data name="log4japp" value="flickr-downloadr.exe" /><log4j:data name="log4net:Identity" value="" /><log4j:data name="log4net:UserName" value="ANDREW-PC\Andrew" /><log4j:data name="log4net:HostName" value="Andrew-PC" /></log4j:properties><log4j:locationInfo class="FloydPink.Flickr.Downloadr.UI.MainClass" method="Quit" file="" line="0" /></log4j:event>

```

**Comment by floydpink** [comment]
The Preferences window allows to changing the log level (as detailed here: https://github.com/flickr-downloadr/flickr-downloadr-gtk/issues/50#issuecomment-292722777)

**Comment by wiccked** [comment]
I was having this happen, and figured out (eventually) that it was a really long filename causing it.  I tried the image in question by itself and it caused the same silent crash.  I renamed it, and moved the name to the description and it was fine then.  However, the really annoying part is that you have no idea when it's stopped!  I was lucky with this one, that it was at the start of the download.  (I've been doing it album by album).  It would be awesome if there was a way to skip long filenames and produce a list at the end, for you to download manually.

**Comment by cutedaffodil** [comment]
@wiccked - which OS are you on? 

Also, could you please share the length of the name for the failing photo along with the length of the full path to the download folder?

**Comment by wiccked** [comment]
windows10,
The filename was originally "This little dog has been into the creek three times!  The first time she walked in- because I was in there, the next two times she jumped in! Because I was still in there ;) very cute little miss."
the path was "E:\My Pictures\Photos\flickr\flickr-downloadr-[Sunshine Coast]-2018-11-17_16-27-45"
