### ISSUE TITLE
How to use your secrects.cs.in file?

### ISSUE THREAD

**Issue by HardySoftware** [flickr-downloadr/flickr-downloadr-gtk#82]
I assume you used it to produce actual secrects.cs from it, but how?

Thanks

**Comment by floydpink** [comment]
You'd need to create an API Key from flickr - using this guide: https://www.flickr.com/services/developer/api/

That will give you the raw/unencrypted values for `ConsumerKey` and `ConsumerSecret` - these cannot applied into `Secret.cs` yet (we need to encrypt them using a `SharedSecret`).

The `SharedSecret` is just a random string (with alphanumeric characters) and use that as the `CryptKey` within [this unit test](https://github.com/flickr-downloadr/flickr-downloadr-gtk/blob/master/source/FloydPink.Flickr.Downloadr.UnitTests/HelperTests/CryptTests.cs#L9) to generate the encrypted values for your flickr API key (`ConsumerKey` and `ConsumerSecret`) and update those into `Secret.cs` which should look like this:

```csharp
namespace FloydPink.Flickr.Downloadr.Bootstrap
{
    public static class Secrets
    {
        // a random secret string
        public const string SharedSecret = "";

        // your API key from flickr, encrypted using the "shared" secret above
        public const string ConsumerKey = "";

        // your API secret from flickr, encrypted using the "shared" secret above
        public const string ConsumerSecret = "";
    }
}
```

**Comment by HardySoftware** [comment]
Thanks a lot for the explanation - I figured out they key and secret from Flickr developer Api portal. The missing piece is shared secret.

I am wondering if you include code comments in this file just as you described, it will make everyone easy to grasp :-)

Cheers!

**Comment by floydpink** [comment]
Great idea, @HardySoftware - would you like to create a pull request with this change? :)
