### ISSUE TITLE
Unhandled exception login

### ISSUE THREAD

**Issue by gianky69** [flickr-downloadr/flickr-downloadr-gtk#87]
![image](https://user-images.githubusercontent.com/5670189/48545976-6b3b8980-e8c7-11e8-813a-efdf2f3679e4.png)
With latest beta on Windows 10 during login

**Comment by floydpink** [comment]
Can you please update the Preferences to log more details and paste the log file contents here?

**Comment by gianky69** [comment]
Log in attachment
[flickrdownloadr.log](https://github.com/flickr-downloadr/flickr-downloadr-gtk/files/2595303/flickrdownloadr.log)

**Comment by cutedaffodil** [comment]
Looks like you might be behind a proxy? Can you try from another network/machine?

```
DotNetOpenAuth.Messaging.ProtocolException: Web request to 'https://www.flickr.com/services/oauth/request_token' failed. ---> System.Net.WebException: Errore del server remoto: (407) Richiesta autenticazione proxy.
```

**Comment by gianky69** [comment]
Sorry, I need to operate via proxy
