### ISSUE TITLE
How to download multiple or all albums at once?

### ISSUE THREAD

**Issue by van-tienhoang** [flickr-downloadr/flickr-downloadr-gtk#88]
Hi, I see the application can select one album e time. Is it possible to make it get all album/multiple albums at once? and where to start the code if possible?
Thank you

**Comment by floydpink** [comment]
Thank you for offering to add this enhancement, @van-tienhoang 

Here is what my thoughts are on how this could be implemented:

Currently the UX is such that selection of a single album (or all the public/private photos) done on the LandingWindow then loads all the photos from that bucket into the BrowserWindow for single/multi-selecting the photos to be downloaded. 

Perhaps, we could add a toggle-button on the LandingWindow that enables “the selection and download of multiple albums in one go” - say “Download Multiple Albums” or something. 

That toggle button could toggle all the buttons on LandingWindow to show the ones similar to the selection buttons on BrowserWindow - perhaps this will disable the “All Public photos” and “All Private photos” buckets at the top of the window from being selectable. 

One the selection of albums are done, the user could click a “Download selected albums” button to directly invoke a looping over of all albums to get all photos in them and then calling the DownloadPhotos method on the DownloadLogic.cs module. 

The app is using an MVP design pattern and uses GTK# for the views currently (which you might have already seen). 

Let me know what you think. And once again thanks for looking into this.

**Comment by cutedaffodil** [comment]
Closed by 8964d5be7acc6dae7cd9c25da2afffc1e0c04a29
