### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by wiccked** [flickr-downloadr/flickr-downloadr-gtk#90]
![image](https://user-images.githubusercontent.com/870500/48820331-3a17f900-eda0-11e8-8e20-64b20ced9225.png)
I just received errors when an album completed download.
I have now changed the logging level and I'm redownloading the same set.
[flickrdownloadr.log](https://github.com/flickr-downloadr/flickr-downloadr-gtk/files/2602744/flickrdownloadr.log)
and got the error again!  Please let me know if you would like any more info.

**Comment by cutedaffodil** [comment]
@wiccked - thank you very much for reporting this along with the log file.

It looks like the log file still did not get the error itself - if it is not too much trouble, could you please reproduce the error one more time and upload the log file yet another time?

really appreciate your help. 🙂
